### ISSUE TITLE
Add configuration: choose which fields should be preserved

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/flatten-tool#302]
Right now, flatten-tool will preserve every field that's in the source data. If a data source contains a lot of fields that aren't relevant to a particular use case (eg publisher-specific fields on top of standard fields), then this makes the output data harder to work with. 

We should add the ability for a user to specify which fields they want to preserve. During sprint prep, we discussed that this could be by means of supplying an additional file that contains a list of fields. 

This starts the output configuration feature set that #131 speaks to.

**Comment by rhiaro** [comment]
Implementing this by adding a cli argument that lets the user specify the JSON paths to include as a file, with one path per line. 

* Paths need to be exact matches to a field in the data, not partial fieldnames, ie. `tender/doc` will *not* match `tender/documents`.
* Paths to a field for which the value is an object (or array of objects) will automatically include all child paths. To be selective about the children, they need to be specified individually in the input.

Plus from https://github.com/OpenDataServices/flatten-tool/pull/305#issuecomment-493975579:

* Input paths should not include array indices.
* Warnings are issued for input paths which have no matches in the data.
* Warnings are issued for input paths which have no match in the schema, if a schema is provided.

So far I don't see a need for a flag so that "the user can switch between specifying either a list of paths, or a list of path prefixes" (https://github.com/OpenDataServices/flatten-tool/pull/305#issuecomment-493940382) because paths in the data are either to a field with a value, or to an object with child fields, but not both (please correct me if this is wrong). So the user can input a mix of full paths and parent paths without needing to choose one or the other.

**Comment by jpmckinney** [comment]
Sounds good! The use case for that last flag is very narrow, and I don't know a specific user asking for it - so agree that it's not needed.
