### ISSUE TITLE
Inconsistency between flatten which defaults to main and unflatten which defaults to release

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#34]
If this codebase is destined to support multiple standards, I would suggest that the defaults are made generic: https://github.com/open-contracting/flattening-ocds/issues/40

**Comment by practicalparticipation** [comment]
I've been testing the tool using the CSV file from http://lin-360giving.aptivate.org/ and the header row:
  ocid,title,description,funder,fundingOrganization/id,fundingOrganization/name,recipient,recipientOrganization/id,recipientOrganization/name,currency,amountAppliedFor,amountAwarded,recipientOrganization/charityNumber,recipientOrganization/companyNumber,applicationDate/startDate,awardDate/startDate,plannedDates/startDate,plannedDates/endDate,beneficiary/country,beneficiary/location/lat,beneficiary/location/long,fromOpenCall,relatedActivity,lastModified,url,recipientOrganization/address

In order to see how the script copes with large files. So far script has been running for 20 minutes. If completes successfully, then may still need to include some sort of large file warning to users.
