### ISSUE TITLE
just a thought - pandas instead of openpyxl

### ISSUE THREAD

**Issue by birdsarah** [OpenDataServices/flatten-tool#61]
Hi,

I have not given this a lot of thought, but just wanted to throw out there that pandas has really nice features for reading to/from csv, json, excel.

http://pandas.pydata.org/pandas-docs/dev/io.html
http://pandas.pydata.org/pandas-docs/dev/io.html#io-excel

Happy to chat about it / mini-sprint around OpenDataCon?

**Comment by Bjwebb** [comment]
Yes, would be good to talk about at OpenDataCon.

Part of the reason for chosing tools like openpyxl instead of pandas, is that they have support for specific features of the output format, e.g. for openpyxl we can do validation (which I don't think Pandas does) https://openpyxl.readthedocs.org/en/latest/validation.html https://github.com/OpenDataServices/flatten-tool/issues/44. On the other hand, we're not actually using that yet!

**Comment by birdsarah** [comment]
Pandas does use openpyxl so I wonder if that would still be possible.
