### ISSUE TITLE
Dealing with company numbers that start with 0

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/flatten-tool#87]
(I think this is flatten-tool)

Quite often , in 360, a spreadsheet will remove the leading 0 of a company number (eg: https://beta.companieshouse.gov.uk/company/09506232 becomes 9506232)

This may in turn invalidate the company number

We should look to account for this.  AFAIK, all company numbers should  be 8 digits long (see: https://www.gov.uk/government/news/registration-of-company-number-10000000)

**Comment by Bjwebb** [comment]
Are you suggesting that flatten-tool should be fixing the data? (rather than just us flagging the error in Cove?) I'm not sure how this fits with our plan to improve data at source. I understand that there are some cases we want to handle due to the limitations of spreadsheet (dates may be a similar one), but I think we might need to discuss where the line lies.

**Comment by stevieflow** [comment]
I guess the other way to look at this is that this field should / could be a string of 8 characters ?

**Comment by Bjwebb** [comment]
We could enforce that in the schema, and Cove would emit a validation error. Not sure how difficult it would then be to get publishers to fix it.

**Comment by stevieflow** [comment]
@bjwebb have flagged that in https://github.com/ThreeSixtyGiving/standard/issues/121

Therefore - do we need to persist with this issue?

**Comment by Bjwebb** [comment]
@stevieflow Happy for you to close this issue if you want. OTOH, we may want to discuss whether flatten-tool should be fixing this problem in data, in addition to Cove validating it.
